# Generated by Django 5.0.6 on 2024-06-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_city_created_at_city_updated_at_country_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_available_for_rent',
            field=models.BooleanField(default=False),
        ),
    ]
